[package]
name = "cvport"
version = "0.1.0"
authors = ["Jonny <jonnym22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
